name: Continuous integration
on: [push, pull_request]

jobs:
  linux:
    name: Build (Linux, GCC)
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up Python (for SCons)
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -qqq build-essential pkg-config libdrm-dev libxtst-dev libxcomposite-dev
          python -m pip install scons

      - name: Build godot-cpp
        run: |
          cd $GITHUB_WORKSPACE/godot-cpp
          scons target=release platform=linux generate_bindings=yes -j $(nproc) COMMON_FLAGS="-Os -Wl,-Os -Wl,--gc-sections -ffunction-sections -fno-stack-protector -U_FORTIFY_SOURCE -flto -fipa-pta -fdevirtualize-at-ltrans -msse4 -mssse3 -msse3 -msse2 -msse -mfpmath=both -pipe -fno-plt -static-libgcc -fvisibility=hidden"

      - name: Build godot-screengrab
        run: |
          cd $GITHUB_WORKSPACE
          scons target=release platform=linux -j $(nproc) COMMON_FLAGS="-Os -Wl,-Os -Wl,--gc-sections -ffunction-sections -fno-stack-protector -U_FORTIFY_SOURCE -flto -fipa-pta -fdevirtualize-at-ltrans -msse4 -mssse3 -msse3 -msse2 -msse -mfpmath=both -pipe -fno-plt -static-libgcc -fvisibility=hidden"

      - name: Build drmsend
        run: |
          cd $GITHUB_WORKSPACE
          gcc drmsend.c -o drmsend `pkg-config --cflags --libs libdrm` -Os -Wl,-Os -Wl,--gc-sections -ffunction-sections -fno-stack-protector -U_FORTIFY_SOURCE -flto -fipa-pta -fdevirtualize-at-ltrans -msse4 -mssse3 -msse3 -msse2 -msse -mfpmath=both -pipe -fno-plt -static-libgcc -fvisibility=hidden -s

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: screengrab-shared
          path: |
            project/gdnative/linux/libscreengrab.so
            project/gdnative/compwindow.gdns
            project/gdnative/screengrab.gdnlib
            project/gdnative/screengrab.gdns
            drmsend
          if-no-files-found: error
